# Generated by Django 3.2.11 on 2022-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_drivers_license',
            field=models.BooleanField(default=True),
        ),
    ]
