# Generated by Django 4.0.4 on 2022-04-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_usercar_first_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
