# Generated by Django 3.2.11 on 2022-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_customuser_has_drivers_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='acquired_license_date',
            field=models.DateField(null=True),
        ),
    ]
