# Generated by Django 4.0.4 on 2022-04-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_name_carmodel_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='model_name',
            new_name='car_model_name',
        ),
    ]
