# Generated by Django 4.0.4 on 2022-04-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carmodel_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_model_name',
            new_name='name',
        ),
    ]
