# Generated by Django 4.0.4 on 2022-04-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_car_model_name_carmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='usercar',
            name='deleted_at',
        ),
    ]
