# Generated by Django 4.0.4 on 2022-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_carbrand_deleted_at_carmodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usercar',
            name='created_at',
        ),
    ]
